# Generated by Django 2.0 on 2019-04-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190410_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExecutiveRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('from_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Campaign')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Executive')),
            ],
        ),
    ]
