# Generated by Django 2.0 on 2019-04-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190422_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectCampaignRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(auto_now_add=True)),
                ('released', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Campaign')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Prospect')),
            ],
        ),
    ]
