# Generated by Django 2.0 on 2019-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_prospectcampaignrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectcampaignrelation',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Prospect'),
        ),
        migrations.AlterUniqueTogether(
            name='prospectcampaignrelation',
            unique_together={('prospect', 'campaign')},
        ),
    ]
