# Generated by Django 2.0 on 2019-04-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190424_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospectcampaignrelation',
            unique_together=set(),
        ),
    ]
