# Generated by Django 2.0 on 2019-04-28 23:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20190424_1432'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prospect',
            managers=[
                ('non_assigned_prospects', django.db.models.manager.Manager()),
            ],
        ),
    ]
