# Generated by Django 2.0 on 2019-04-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20190428_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignexecutiverelation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignexecutiverelation',
            name='executive',
        ),
        migrations.AlterUniqueTogether(
            name='dnc',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dnc',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='dnc',
            name='executive',
        ),
        migrations.RemoveField(
            model_name='dnc',
            name='prospect',
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='executive',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='prospect',
        ),
        migrations.AlterModelManagers(
            name='prospect',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='assigned_campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='prospects',
            field=models.ManyToManyField(blank=True, through='portal.ProspectCampaignRelation', to='portal.Prospect'),
        ),
        migrations.AlterField(
            model_name='prospectcampaignrelation',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Prospect'),
        ),
        migrations.DeleteModel(
            name='CampaignExecutiveRelation',
        ),
        migrations.DeleteModel(
            name='DNC',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
