# Generated by Django 2.0 on 2019-04-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20190428_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospectcampaignrelation',
            unique_together={('prospect', 'campaign')},
        ),
    ]
