# Generated by Django 2.0 on 2019-04-28 23:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20190428_2354'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
