# Generated by Django 2.0 on 2019-04-29 00:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20190428_2358'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
                ('my_search', django.db.models.manager.Manager()),
            ],
        ),
    ]
