# Generated by Django 2.0 on 2019-04-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20190429_0026'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
            ],
        ),
    ]
