# Generated by Django 2.0 on 2019-04-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20190429_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('Lead', 'Lead'), ('View', 'View'), ('DNC', 'DNC')], max_length=20)),
                ('details', models.TextField()),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Executive')),
            ],
        ),
        migrations.RenameField(
            model_name='prospectcampaignrelation',
            old_name='released',
            new_name='attempted',
        ),
        migrations.AddField(
            model_name='prospectcampaignrelation',
            name='attempt_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.AttemptResult'),
        ),
    ]
