# Generated by Django 2.0 on 2019-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_attemptresult_prospect_campaign_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSepration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='separation_files/')),
                ('details', models.TextField(blank=True)),
                ('campaign', models.ManyToManyField(blank=True, to='portal.Campaign')),
            ],
        ),
        migrations.RemoveField(
            model_name='prospectcampaignrelation',
            name='attempt_result',
        ),
        migrations.AddField(
            model_name='prospect',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospectcampaignrelation',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attemptresult',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
